Simulink.defineIntEnumType( 'EventSts1', ...
   {'EventSts_NoAct','EventSts_Act','EventSts_CancleChime'}, ...
   [0 1 2], ...
   'DefaultValue', 'EventSts_NoAct', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

