Simulink.defineIntEnumType( 'CmprtMdRfCtrlSwSlctStat1', ...
   {'NoModeOn','Mode1On','Mode2On','Mode3On','Mode4On','Mode5On','Mode6On','Mode7On','Mode8On','Mode9On','Mode10On','Mode11On','Mode12On','Mode13On','Mode14On','Mode15On'}, ...
   [0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15], ...
   'DefaultValue', 'NoModeOn', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'CmprtMdRfCtrlSwSlctStat2', ...
   {'NoModeOn1','Mode16On','Mode17On','Mode18On','Mode19On','Mode20On','Mode21On','Mode22On','Mode23On','Mode24On','Mode25On','Mode26On','Mode27On','Mode28On','Mode29On','Mode30On','Mode31On','Mode32On'}, ...
   [0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17], ...
   'DefaultValue', 'NoModeOn1', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'EventSts1', ...
   {'EventSts_NoAct','EventSts_Act','EventSts_CancleChime'}, ...
   [0 1 2], ...
   'DefaultValue', 'EventSts_NoAct', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'IfVeSMSeStNumConfig', ...
   {'SeatNum4Config','SeatNum6Config','SeatNum7Config','SeatNum4PConfig','SeatNumNDLBLow','SeatNumNDLBHigh'}, ...
   [0 1 2 3 4 5], ...
   'DefaultValue', 'SeatNum4Config', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'MdTp1', ...
   {'MdTp_None','MdTp_EzeEntry','MdTp_EzeExt','MdTp_Vip','MdTp_Lug','MdTp_Recovery','MdTp_Intimacy','MdTp_Family','MdTp_Lying','MdTp_LgrstOpenLt','MdTp_LgrstCloseLt','MdTp_LgrstOpenRt','MdTp_LgrstCloseRt'}, ...
   [0 1 2 3 4 5 6 7 8 9 10 11 12], ...
   'DefaultValue', 'MdTp_None', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'SRSCurMode1', ...
   {'SRSMode_None','SRSMode_EZEEntry','SRSMode_EzeExt','SRSMode_LfVip','SRSMode_RtVip','SRSMode_AllVip','SRSMode_LfLug','SRSMode_RtLug','SRSMode_AllLug','SRSMode_IntimacyL','SRSMode_FamilyR','SRSMode_FamilyL','SRSMode_RcvyL','SRSMode_RcvyR','SRSMode_LyingL','SRSMode_LyingR','SRSMode_LgrstOpenLt','SRSMode_LgrstCloseLt','SRSMode_LgrstOpenRt','SRSMode_LgrstCloseRt','SRSMode_IntimacyR','SRSMode_EzeEntry4s2L','SRSMode_EzeExt4s2L','SRSMode_EzeEntry4s2R','SRSMode_EzeExt4s2R','SRSMode_EzeEntryAll4sBwd','SRSMode_EzeEntryAll4sFwd'}, ...
   [0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26], ...
   'DefaultValue', 'SRSMode_None', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'SRSIndicatorStat', ...
   {'SRSIndicatorStat_NoIndicator','SRSIndicatorStat_Mode1On','SRSIndicatorStat_Mode2On','SRSIndicatorStat_Mode3On','SRSIndicatorStat_Mode4On','SRSIndicatorStat_Mode5On','SRSIndicatorStat_Mode6On','SRSIndicatorStat_Mode7On','SRSIndicatorStat_Mode8On','SRSIndicatorStat_Mode9On','SRSIndicatorStat_Mode10On','Reserved1','Reserved2','Reserved3','Reserved4','Reserved5'}, ...
   [0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15], ...
   'DefaultValue', 'SRSIndicatorStat_NoIndicator', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'SRSMode1', ...
   {'SRSSlctSwStat_None','SRSSlctSwStat_EzeEntry','SRSSlctSwStat_EzeExt','SRSSlctSwStat_LfVip','SRSSlctSwStat_RtVip','SRSSlctSwStat_AllVip','SRSSlctSwStat_LfLug','SRSSlctSwStat_RtLug','SRSSlctSwStat_AllLug','SRSSlctSwStat_IntimacyL','SRSSlctSwStat_FamilyR','SRSSlctSwStat_FamilyL','SRSSlctSwStat_RcvyL','SRSSlctSwStat_RcvyR','SRSSlctSwStat_LyingL','SRSSlctSwStat_LyingR','SRSSlctSwStat_LgrstOpenLt','SRSSlctSwStat_LgrstCloseLt','SRSSlctSwStat_LgrstOpenRt','SRSSlctSwStat_LgrstCloseRt','SRSSlctSwStat_IntimacyR','SRSSlctSwStat_EzeEntry4s2L','SRSSlctSwStat_EzeExt4s2L','SRSSlctSwStat_EzeEntry4s2R','SRSSlctSwStat_EzeExt4s2R','SRSSlctSwStat_EzeEntryAll4sBwd','SRSSlctSwStat_EzeEntryAll4sFwd'}, ...
   [0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26], ...
   'DefaultValue', 'SRSSlctSwStat_None', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'SRSSlctSwIndTyp', ...
   {'IndicationOff','FlashRate1','FlashRate2','Continuous'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'IndicationOff', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'SRSSlctSwStat1', ...
   {'NoSwitchSelected','Switch1Mode','Switch2Mode','Switch3Mode','Switch4Mode','Switch5Mode','Switch6Mode','Switch7Mode','Switch8Mode','Switch9Mode','Switch10Mode','Reserved'}, ...
   [0 1 2 3 4 5 6 7 8 9 10 11], ...
   'DefaultValue', 'NoSwitchSelected', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

