Simulink.defineIntEnumType( 'MdRspLocal1', ...
   {'MdRsp_None','MdRsp_RecallSuccessfully','MdRsp_RecallUnsuccessfully_LocalInterrupt','MdRsp_RecallUnsuccessfully_Error','MdRsp_RecallOngoing','MdRsp_RecallHalt'}, ...
   [0 1 2 3 4 5], ...
   'DefaultValue', 'MdRsp_None', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

