Simulink.defineIntEnumType( 'IfVeSMSeStNumConfig', ...
   {'SeatNum4Config','SeatNum6Config','SeatNum7Config','SeatNum4PConfig'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'SeatNum4Config', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'PowerMode1', ...
   {'PowerMode_Off','PowerMode_Acc','PowerMode_Run','PowerMode_Crank','PowerMode_Invalid'}, ...
   [0 1 2 3 4], ...
   'DefaultValue', 'PowerMode_Off', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'SeatChldLkSt', ...
   {'ChldLkSt_NoActive','ChldLkSt_Lock','ChldLkSt_Unlock'}, ...
   [0 1 2], ...
   'DefaultValue', 'ChldLkSt_NoActive', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'SeatOccupiedSts1', ...
   {'SeatOccupiedSts_Unknown','SeatOccupiedSts_Empty','SeatOccupiedSts_Occupied','SeatOccupiedSts_DataNotAvailable'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'SeatOccupiedSts_Unknown', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

