Simulink.defineIntEnumType( 'PowerMode1', ...
   {'PowerMode_Off','PowerMode_Acc','PowerMode_Run','PowerMode_Crank','PowerMode_Invalid'}, ...
   [0 1 2 3 4], ...
   'DefaultValue', 'PowerMode_Off', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

