Simulink.defineIntEnumType( 'DrvStCshnRrUpwdDnwdPosV_MSM_2L', ...
   {'Valid','Invalid'}, ...
   [0 1], ...
   'DefaultValue', 'Valid', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'DrvStFrwdBkwdPosV_MSM_2L', ...
   {'Valid','Invalid'}, ...
   [0 1], ...
   'DefaultValue', 'Valid', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

