Simulink.defineIntEnumType( 'CmprtMdHMIReqExt2Tp1', ...
   {'CmprtMdHMIReqExt2Tp_NoAction','CmprtMdHMIReqExt2Tp_Mode46','CmprtMdHMIReqExt2Tp_Mode47','CmprtMdHMIReqExt2Tp_Mode48','CmprtMdHMIReqExt2Tp_Mode49','CmprtMdHMIReqExt2Tp_Mode50','CmprtMdHMIReqExt2Tp_Mode51','CmprtMdHMIReqExt2Tp_Mode52','CmprtMdHMIReqExt2Tp_Mode53','CmprtMdHMIReqExt2Tp_Mode54','CmprtMdHMIReqExt2Tp_Mode55','CmprtMdHMIReqExt2Tp_Mode56','CmprtMdHMIReqExt2Tp_Mode57','CmprtMdHMIReqExt2Tp_Mode58','CmprtMdHMIReqExt2Tp_Mode59','CmprtMdHMIReqExt2Tp_Mode60','CmprtMdHMIReqExt2Tp_Mode61','CmprtMdHMIReqExt2Tp_Mode62','CmprtMdHMIReqExt2Tp_Mode63','CmprtMdHMIReqExt2Tp_Mode64','CmprtMdHMIReqExt2Tp_Mode65','CmprtMdHMIReqExt2Tp_Mode66','CmprtMdHMIReqExt2Tp_Mode67','CmprtMdHMIReqExt2Tp_Mode68','CmprtMdHMIReqExt2Tp_Mode69','CmprtMdHMIReqExt2Tp_Mode70','CmprtMdHMIReqExt2Tp_Mode71','CmprtMdHMIReqExt2Tp_Mode72','CmprtMdHMIReqExt2Tp_Mode73','CmprtMdHMIReqExt2Tp_Mode74','CmprtMdHMIReqExt2Tp_Mode75','CmprtMdHMIReqExt2Tp_Mode76','CmprtMdHMIReqExt2Tp_Mode77','CmprtMdHMIReqExt2Tp_Mode78','CmprtMdHMIReqExt2Tp_Mode79','CmprtMdHMIReqExt2Tp_Mode80','CmprtMdHMIReqExt2Tp_Mode81','CmprtMdHMIReqExt2Tp_Mode82','CmprtMdHMIReqExt2Tp_Mode83','CmprtMdHMIReqExt2Tp_Mode84','CmprtMdHMIReqExt2Tp_Mode85','CmprtMdHMIReqExt2Tp_Mode86','CmprtMdHMIReqExt2Tp_Mode87','CmprtMdHMIReqExt2Tp_Mode88','CmprtMdHMIReqExt2Tp_Mode89','CmprtMdHMIReqExt2Tp_Mode90','CmprtMdHMIReqExt2Tp_Mode91','CmprtMdHMIReqExt2Tp_Mode92','CmprtMdHMIReqExt2Tp_Mode93','CmprtMdHMIReqExt2Tp_Mode94','CmprtMdHMIReqExt2Tp_Mode95','CmprtMdHMIReqExt2Tp_Mode96','CmprtMdHMIReqExt2Tp_Mode97','CmprtMdHMIReqExt2Tp_Mode98','CmprtMdHMIReqExt2Tp_Mode99','CmprtMdHMIReqExt2Tp_Mode100','CmprtMdHMIReqExt2Tp_Mode101','CmprtMdHMIReqExt2Tp_Mode102','CmprtMdHMIReqExt2Tp_Mode103','CmprtMdHMIReqExt2Tp_Mode104','CmprtMdHMIReqExt2Tp_Mode105','CmprtMdHMIReqExt2Tp_Mode106','CmprtMdHMIReqExt2Tp_Mode107','CmprtMdHMIReqExt2Tp_Mode108','CmprtMdHMIReqExt2Tp_Mode109','CmprtMdHMIReqExt2Tp_Mode110','CmprtMdHMIReqExt2Tp_Mode111','CmprtMdHMIReqExt2Tp_Mode112','CmprtMdHMIReqExt2Tp_Mode113','CmprtMdHMIReqExt2Tp_Mode114','CmprtMdHMIReqExt2Tp_Mode115','CmprtMdHMIReqExt2Tp_Mode116','CmprtMdHMIReqExt2Tp_Mode117','CmprtMdHMIReqExt2Tp_Mode118','CmprtMdHMIReqExt2Tp_Mode119','CmprtMdHMIReqExt2Tp_Mode120'}, ...
   [0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75], ...
   'DefaultValue', 'CmprtMdHMIReqExt2Tp_NoAction', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'CmprtMdHMIReqExtTp1', ...
   {'CmprtMdHMIReqExtTp_NoAction','CmprtMdHMIReqExtTp_Mode15','CmprtMdHMIReqExtTp_Mode16','CmprtMdHMIReqExtTp_Mode17','CmprtMdHMIReqExtTp_Mode18','CmprtMdHMIReqExtTp_Mode19','CmprtMdHMIReqExtTp_Mode20','CmprtMdHMIReqExtTp_Mode21','CmprtMdHMIReqExtTp_Mode22','CmprtMdHMIReqExtTp_Mode23','CmprtMdHMIReqExtTp_Mode24','CmprtMdHMIReqExtTp_Mode25','CmprtMdHMIReqExtTp_Mode26','CmprtMdHMIReqExtTp_Mode27','CmprtMdHMIReqExtTp_Mode28','CmprtMdHMIReqExtTp_Mode29','CmprtMdHMIReqExtTp_Mode30','CmprtMdHMIReqExtTp_Mode31','CmprtMdHMIReqExtTp_Mode32'}, ...
   [0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18], ...
   'DefaultValue', 'CmprtMdHMIReqExtTp_NoAction', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'CmprtMdHMIReqTp1', ...
   {'CmprtMdHMIReqTp_NoAction','CmprtMdHMIReqTp_Mode1','CmprtMdHMIReqTp_Mode2','CmprtMdHMIReqTp_Mode3','CmprtMdHMIReqTp_Mode4','CmprtMdHMIReqTp_Mode5','CmprtMdHMIReqTp_Mode6','CmprtMdHMIReqTp_Mode7','CmprtMdHMIReqTp_Mode8','CmprtMdHMIReqTp_Mode9','CmprtMdHMIReqTp_Mode10','CmprtMdHMIReqTp_Mode11','CmprtMdHMIReqTp_Mode12','CmprtMdHMIReqTp_Mode13','CmprtMdHMIReqTp_Mode14','CmprtMdHMIReqTp_Stop'}, ...
   [0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15], ...
   'DefaultValue', 'CmprtMdHMIReqTp_NoAction', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'EZESwReq1', ...
   {'EZESwReq_inactive','EZE_IN','EZE_OUT'}, ...
   [0 1 2], ...
   'DefaultValue', 'EZESwReq_inactive', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'IfVeSMSeStNumConfig', ...
   {'SeatNum4Config','SeatNum6Config','SeatNum7Config','SeatNum4PConfig','SeatNumNDLBLow','SeatNumNDLBHigh'}, ...
   [0 1 2 3 4 5], ...
   'DefaultValue', 'SeatNum4Config', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'LckUlckActvtFunc1', ...
   {'ActvFunc_NoAct','ActvFunc_PwrDorLckSw','ActvFunc_DrvKeyCyl','ActvFunc_RCSwitch','ActvFunc_Emergency','ActvFunc_ActvRmtKeyfob','ActvFunc_PasvRmtKeyfob','ActvFunc_EnhancedService','ActvFunc_DelyLocking','ActvFunc_Relocking','ActvFunc_LockOutPrevent','ActvFunc_ExteriorLockSw','ActvFunc_VKMdev','ActvFunc_ADL','ActvFunc_Lckstupwlck','ActvFunc_PasKeyCyl'}, ...
   [0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15], ...
   'DefaultValue', 'ActvFunc_NoAct', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'LstLckFunc1', ...
   {'LstLckFuncTyp_NoAction','LstLckFuncTyp_PcUndblLock','LstLckFuncTyp_PcUnlock','LstLckFuncTyp_Unlock','LstLckFuncTyp_UnlockDrv','LstLckFuncTyp_UnlockPas','LstLckFuncTyp_UnlockLr','LstLckFuncTyp_UnlockRr','LstLckFuncTyp_UnlockCargoLftgt','LstLckFuncTyp_UnlockDrvSd','LstLckFuncTyp_UnlockPasSd','LstLckFuncTyp_UnlockNonDrv','LstLckFuncTyp_UnlockAll','LstLckFuncTyp_Lock','LstLckFuncTyp_LockAll','LstLckFuncTyp_DblLock','LstLckFuncTyp_UnDblLock'}, ...
   [0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16], ...
   'DefaultValue', 'LstLckFuncTyp_NoAction', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'LugSelectSw1', ...
   {'LugSelectSw_NoAction','LugSelectSw_Left','LugSelectSw_Right','LugSelectSw_All'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'LugSelectSw_NoAction', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'MdReqTp1', ...
   {'MdReqTp_NoAction','MdReqTp_Start','MdReqTp_Stop','MdReqTp_Cancel'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'MdReqTp_NoAction', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'MdTp1', ...
   {'MdTp_None','MdTp_EzeEntry','MdTp_EzeExt','MdTp_Vip','MdTp_Lug','MdTp_Recovery','MdTp_Intimacy','MdTp_Family','MdTp_Lying','MdTp_LgrstOpenLt','MdTp_LgrstCloseLt','MdTp_LgrstOpenRt','MdTp_LgrstCloseRt'}, ...
   [0 1 2 3 4 5 6 7 8 9 10 11 12], ...
   'DefaultValue', 'MdTp_None', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'PowerMode1', ...
   {'PowerMode_Off','PowerMode_Acc','PowerMode_Run','PowerMode_Crank','PowerMode_Invalid'}, ...
   [0 1 2 3 4], ...
   'DefaultValue', 'PowerMode_Off', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'SRSCurMode1', ...
   {'SRSMode_None','SRSMode_EZEEntry','SRSMode_EzeExt','SRSMode_LfVip','SRSMode_RtVip','SRSMode_AllVip','SRSMode_LfLug','SRSMode_RtLug','SRSMode_AllLug','SRSMode_IntimacyL','SRSMode_FamilyR','SRSMode_FamilyL','SRSMode_RcvyL','SRSMode_RcvyR','SRSMode_LyingL','SRSMode_LyingR','SRSMode_LgrstOpenLt','SRSMode_LgrstCloseLt','SRSMode_LgrstOpenRt','SRSMode_LgrstCloseRt','SRSMode_IntimacyR','SRSMode_EzeEntry4s2L','SRSMode_EzeExt4s2L','SRSMode_EzeEntry4s2R','SRSMode_EzeExt4s2R','SRSMode_EzeEntryAll4sBwd','SRSMode_EzeEntryAll4sFwd'}, ...
   [0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26], ...
   'DefaultValue', 'SRSMode_None', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'SRSMode1', ...
   {'SRSSlctSwStat_None','SRSSlctSwStat_EzeEntry','SRSSlctSwStat_EzeExt','SRSSlctSwStat_LfVip','SRSSlctSwStat_RtVip','SRSSlctSwStat_AllVip','SRSSlctSwStat_LfLug','SRSSlctSwStat_RtLug','SRSSlctSwStat_AllLug','SRSSlctSwStat_IntimacyL','SRSSlctSwStat_FamilyR','SRSSlctSwStat_FamilyL','SRSSlctSwStat_RcvyL','SRSSlctSwStat_RcvyR','SRSSlctSwStat_LyingL','SRSSlctSwStat_LyingR','SRSSlctSwStat_LgrstOpenLt','SRSSlctSwStat_LgrstCloseLt','SRSSlctSwStat_LgrstOpenRt','SRSSlctSwStat_LgrstCloseRt','SRSSlctSwStat_IntimacyR','SRSSlctSwStat_EzeEntry4s2L','SRSSlctSwStat_EzeExt4s2L','SRSSlctSwStat_EzeEntry4s2R','SRSSlctSwStat_EzeExt4s2R','SRSSlctSwStat_EzeEntryAll4sBwd','SRSSlctSwStat_EzeEntryAll4sFwd'}, ...
   [0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26], ...
   'DefaultValue', 'SRSSlctSwStat_None', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'SeatOccupiedSts1', ...
   {'SeatOccupiedSts_Unknown','SeatOccupiedSts_Empty','SeatOccupiedSts_Occupied','SeatOccupiedSts_DataNotAvailable'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'SeatOccupiedSts_Unknown', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'SrcReqTp1', ...
   {'SrcReqTp_None','SrcReqTp_Local','SrcReqTp_HMI2L','SrcReqTp_HMI2R','SrcReqTp_HMI','SrcReqTp_Remote','SrcReqTp_SRS'}, ...
   [0 1 2 3 4 5 6], ...
   'DefaultValue', 'SrcReqTp_None', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'VehMovState1', ...
   {'VehMvSts_Parked','VehMvSts_Neutral','VehMvSts_Forward','VehMvSts_Reverse','VehMvSts_Invalid'}, ...
   [0 1 2 3 4], ...
   'DefaultValue', 'VehMvSts_Parked', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

