Simulink.defineIntEnumType( 'IfVeSMSeStNumConfig', ...
   {'SeatNum4Config','SeatNum6Config','SeatNum7Config','SeatNum4PConfig'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'SeatNum4Config', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

