Simulink.defineIntEnumType( 'CmprtMdHMIReqTp1', ...
   {'CmprtMdHMIReqTp_NoAction','CmprtMdHMIReqTp_Mode1','CmprtMdHMIReqTp_Mode2','CmprtMdHMIReqTp_Mode3','CmprtMdHMIReqTp_Mode4','CmprtMdHMIReqTp_Mode5','CmprtMdHMIReqTp_Mode6','CmprtMdHMIReqTp_Mode7','CmprtMdHMIReqTp_Mode8','CmprtMdHMIReqTp_Mode9','CmprtMdHMIReqTp_Mode10','CmprtMdHMIReqTp_Mode11','CmprtMdHMIReqTp_Mode12','CmprtMdHMIReqTp_Mode13','CmprtMdHMIReqTp_Mode14','CmprtMdHMIReqTp_Stop'}, ...
   [0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15], ...
   'DefaultValue', 'CmprtMdHMIReqTp_NoAction', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'IfVeSMSeStNumConfig', ...
   {'SeatNum4Config','SeatNum6Config','SeatNum7Config','SeatNum4PConfig','SeatNumNDLBLow','SeatNumNDLBHigh'}, ...
   [0 1 2 3 4 5], ...
   'DefaultValue', 'SeatNum4Config', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'MdReqTp1', ...
   {'MdReqTp_NoAction','MdReqTp_Start','MdReqTp_Stop','MdReqTp_Cancel'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'MdReqTp_NoAction', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

