Simulink.defineIntEnumType( 'SRSIndicatorStat', ...
   {'SRSIndicatorStat_NoIndicator','SRSIndicatorStat_Mode1On','SRSIndicatorStat_Mode2On','SRSIndicatorStat_Mode3On','SRSIndicatorStat_Mode4On','SRSIndicatorStat_Mode5On','SRSIndicatorStat_Mode6On','SRSIndicatorStat_Mode7On','SRSIndicatorStat_Mode8On','SRSIndicatorStat_Mode9On','SRSIndicatorStat_Mode10On','Reserved1','Reserved2','Reserved3','Reserved4','Reserved5'}, ...
   [0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15], ...
   'DefaultValue', 'SRSIndicatorStat_NoIndicator', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'SRSSlctSwIndTyp', ...
   {'IndicationOff','FlashRate1','FlashRate2','Continuous'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'IndicationOff', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

