Simulink.defineIntEnumType( 'FwdBkwdMovmtVirtCtrlReq', ...
   {'FwdBkwdVirtCtrlReq_NoReq','Forward','Backward'}, ...
   [0 1 2], ...
   'DefaultValue', 'FwdBkwdVirtCtrlReq_NoReq', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'LugSelectSw1', ...
   {'LugSelectSw_NoAction','LugSelectSw_Left','LugSelectSw_Right','LugSelectSw_All'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'LugSelectSw_NoAction', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'OtwdInwdMovmtVirtCtrlReq', ...
   {'OtwdInwdVirtCtrlReq_NoReq','Outward','Inward'}, ...
   [0 1 2], ...
   'DefaultValue', 'OtwdInwdVirtCtrlReq_NoReq', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'PosRclRspStat1', ...
   {'PosRclRspStat_None','PosRclRspStat_RecallSuccessfully','PosRclRspStat_RecallUnsuccessfully','PosRclRspStat_RecallOngoing'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'PosRclRspStat_None', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'SeatLmbrSwtchType', ...
   {'CeSMS_LmbrNoAction','CeSMS_LmbrFrwd','CeSMS_LmbrBkwd','CeSMS_LmbrUpwd','CeSMS_LmbrDnwd','CeSMS_LmbrFault'}, ...
   [0 1 2 3 4 255], ...
   'DefaultValue', 'CeSMS_LmbrNoAction', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'TeSMS_e_DrvStMemSwAct', ...
   {'CeSMS_e_Inactive','CeSMS_e_Btn1SwtStorActv','CeSMS_e_Btn1SwtRecallActv','CeSMS_e_Btn2SwtStorActv','CeSMS_e_Btn2SwtRecallActv','CeSMS_e_BtnExitSwtStorActv','CeSMS_e_BtnExitSwtRecallActv'}, ...
   [0 1 2 3 4 5 6], ...
   'DefaultValue', 'CeSMS_e_Inactive', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'TeSMS_e_DrvStMemSwActV', ...
   {'CeSMS_e_Valid','CeSMS_e_Invalid'}, ...
   [0 1], ...
   'DefaultValue', 'CeSMS_e_Valid', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'TeSMS_e_SecLTSeatMemHMIReq', ...
   {'CeSMS_e_NoAction','CeSMS_e_Btn1StroReq','CeSMS_e_Btn2StroReq','CeSMS_e_Btn3StroReq','CeSMS_e_Btn1RecallReq','CeSMS_e_Btn2RecallReq','CeSMS_e_Btn3RecallReq'}, ...
   [0 1 2 3 4 5 6], ...
   'DefaultValue', 'CeSMS_e_NoAction', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'UpwdDnwdMovmtVirtCtrlReq', ...
   {'UpwdDnwdVirtCtrlReq_NoReq','Upward','Downward'}, ...
   [0 1 2], ...
   'DefaultValue', 'UpwdDnwdVirtCtrlReq_NoReq', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

