Simulink.defineIntEnumType( 'SeatOccupiedSts1', ...
   {'SeatOccupiedSts_Unknown','SeatOccupiedSts_Empty','SeatOccupiedSts_Occupied','SeatOccupiedSts_DataNotAvailable'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'SeatOccupiedSts_Unknown', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

