Simulink.defineIntEnumType( 'MdRspLocal1', ...
   {'MdRsp_None','MdRsp_RecallSuccessfully','MdRsp_RecallUnsuccessfully_LocalInterrupt','MdRsp_RecallUnsuccessfully_Error','MdRsp_RecallOngoing','MdRsp_RecallHalt'}, ...
   [0 1 2 3 4 5], ...
   'DefaultValue', 'MdRsp_None', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'SrcReqTp1', ...
   {'SrcReqTp_None','SrcReqTp_Local','SrcReqTp_HMI2L','SrcReqTp_HMI2R','SrcReqTp_HMI','SrcReqTp_Remote','SrcReqTp_SRS'}, ...
   [0 1 2 3 4 5 6], ...
   'DefaultValue', 'SrcReqTp_None', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

