Simulink.defineIntEnumType( 'MdRspLocal2', ...
   {'MdRsp_None','MdRsp_RecallSuccessfully','MdRsp_RecallUnsuccessfully_LocalInterrupt','MdRsp_RecallUnsuccessfully_NonEnghSpace','MdRsp_RecallOngoing','MdRsp_TargetPositionAlready','MdRsp_LowPower','MdRsp_CrashStat','MdRsp_ThdRwOccupt','MdRsp_PosNotLrn','MdRsp_NotParkStat','MdRsp_SpdNotCorrt'}, ...
   [0 1 2 3 4 5 6 7 8 9 10 11], ...
   'DefaultValue', 'MdRsp_None', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'SrcReqTp1', ...
   {'SrcReqTp_None','SrcReqTp_Local','SrcReqTp_HMI2L','SrcReqTp_HMI2R','SrcReqTp_HMI','SrcReqTp_Remote','SrcReqTp_SRS'}, ...
   [0 1 2 3 4 5 6], ...
   'DefaultValue', 'SrcReqTp_None', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

