Simulink.defineIntEnumType( 'DiagAbgDly', ...
   {'NoAbgDly','AbgDly','invalid'}, ...
   [0 1 2], ...
   'DefaultValue', 'NoAbgDly', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'DiagVehMovState', ...
   {'Park','NoPark','invalid1'}, ...
   [0 1 2], ...
   'DefaultValue', 'Park', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'DiagVehSpdAvgDrvn', ...
   {'BelowTwo','AboveTwo','invalid2'}, ...
   [0 1 2], ...
   'DefaultValue', 'BelowTwo', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'EnergyMgLdShdRq1', ...
   {'EnergyMgLdShdRq_NoLdShd','EnergyMgLdShdRq_LdShdLv1','EnergyMgLdShdRq_LdShdLv2','EnergyMgLdShdRq_LdShdLv3','EnergyMgLdShdRq_LdShdLv4'}, ...
   [0 1 2 3 4], ...
   'DefaultValue', 'EnergyMgLdShdRq_NoLdShd', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'IfVeSMSeStNumConfig', ...
   {'SeatNum4Config','SeatNum6Config','SeatNum7Config','SeatNum4PConfig','SeatNumNDLBLow','SeatNumNDLBHigh'}, ...
   [0 1 2 3 4 5], ...
   'DefaultValue', 'SeatNum4Config', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'PosRclRspStat1', ...
   {'PosRclRspStat_None','PosRclRspStat_RecallSuccessfully','PosRclRspStat_RecallUnsuccessfully','PosRclRspStat_RecallOngoing'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'PosRclRspStat_None', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'PowerMode1', ...
   {'PowerMode_Off','PowerMode_Acc','PowerMode_Run','PowerMode_Crank','PowerMode_Invalid'}, ...
   [0 1 2 3 4], ...
   'DefaultValue', 'PowerMode_Off', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'SeatChldLkSt', ...
   {'ChldLkSt_NoActive','ChldLkSt_Lock','ChldLkSt_Unlock'}, ...
   [0 1 2], ...
   'DefaultValue', 'ChldLkSt_NoActive', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'SeatOccupiedSts1', ...
   {'SeatOccupiedSts_Unknown','SeatOccupiedSts_Empty','SeatOccupiedSts_Occupied','SeatOccupiedSts_DataNotAvailable'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'SeatOccupiedSts_Unknown', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'SeatSysVoltSt', ...
   {'CeSMS_SysVoltNormal','CeSMS_SysVoltLow','CeSMS_SysVoltHigh','CeSMS_SysVoltLow1','CeSMS_SysVoltLow2','CeSMS_SysVoltHigh1','CeSMS_SysVoltHigh2'}, ...
   [0 1 2 3 4 5 6], ...
   'DefaultValue', 'CeSMS_SysVoltNormal', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'VehMovState1', ...
   {'VehMvSts_Parked','VehMvSts_Neutral','VehMvSts_Forward','VehMvSts_Reverse','VehMvSts_Invalid'}, ...
   [0 1 2 3 4], ...
   'DefaultValue', 'VehMvSts_Parked', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

