Simulink.defineIntEnumType( 'IfVeSMSeStNumConfig', ...
   {'SeatNum4Config','SeatNum6Config','SeatNum7Config','SeatNum4PConfig'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'SeatNum4Config', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'SeatOccupiedSts1', ...
   {'SeatOccupiedSts_Unknown','SeatOccupiedSts_Empty','SeatOccupiedSts_Occupied','SeatOccupiedSts_DataNotAvailable'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'SeatOccupiedSts_Unknown', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

