Simulink.defineIntEnumType( 'SeatChldLkSt', ...
   {'ChldLkSt_NoActive','ChldLkSt_Lock','ChldLkSt_Unlock'}, ...
   [0 1 2], ...
   'DefaultValue', 'ChldLkSt_NoActive', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

