Simulink.defineIntEnumType( 'MdTp1', ...
   {'MdTp_None','MdTp_EzeEntry','MdTp_EzeExt','MdTp_Vip','MdTp_Lug','MdTp_Recovery','MdTp_Intimacy','MdTp_Family','MdTp_Lying','MdTp_LgrstOpenLt','MdTp_LgrstCloseLt','MdTp_LgrstOpenRt','MdTp_LgrstCloseRt'}, ...
   [0 1 2 3 4 5 6 7 8 9 10 11 12], ...
   'DefaultValue', 'MdTp_None', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'SRSCurMode2', ...
   {'SRSMode_None','SRSMode_EZEEntry','SRSMode_EzeExt','SRSMode_LfVip','SRSMode_RtVip','SRSMode_AllVip','SRSMode_LfLug','SRSMode_RtLug','SRSMode_AllLug','SRSMode_IntimacyL','SRSMode_FamilyR','SRSMode_FamilyL','SRSMode_RcvyL','SRSMode_RcvyR','SRSMode_LyingL','SRSMode_LyingR','SRSMode_LgrstOpenLt','SRSMode_LgrstCloseLt','SRSMode_LgrstOpenRt','SRSMode_LgrstCloseRt','SRSMode_IntimacyR','SRSMode_EzeEntry4s2L','SRSMode_EzeExt4s2L','SRSMode_EzeEntry4s2R','SRSMode_EzeExt4s2R','SRSMode_EzeEntryAll4sBwd','SRSMode_EzeEntryAll4sFwd'}, ...
   [0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26], ...
   'DefaultValue', 'SRSMode_None', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'SrcReqTp1', ...
   {'SrcReqTp_None','SrcReqTp_Local','SrcReqTp_HMI2L','SrcReqTp_HMI2R','SrcReqTp_HMI','SrcReqTp_Remote','SrcReqTp_SRS'}, ...
   [0 1 2 3 4 5 6], ...
   'DefaultValue', 'SrcReqTp_None', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

