Simulink.defineIntEnumType( 'SrcReqTp1', ...
   {'SrcReqTp_None','SrcReqTp_Local','SrcReqTp_HMI2L','SrcReqTp_HMI2R','SrcReqTp_HMI','SrcReqTp_Remote','SrcReqTp_SRS'}, ...
   [0 1 2 3 4 5 6], ...
   'DefaultValue', 'SrcReqTp_None', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

